name: Test Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hello message
        run: echo "Hello, world!"
      - name: Echo goodbye message
        run: echo "I am done, goodbye!"
